=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio7/ejercicio7.6.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT arrel (a, b, c, d, d, e)>
<!ELEMENT a EMPTY>
<!ELEMENT b (#PCDATA)>
<!ELEMENT c EMPTY>
<!ELEMENT d (#PCDATA)>
<!ELEMENT e (f*)>
<!ELEMENT f (g?, h?)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT h (#PCDATA)>

=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio7/ejercicio7.6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arrel SYSTEM "ejercicio7.6.dtd">
<arrel>
    <a></a>
    <b><![CDATA[
void call()
{
int res;
init_module(&res);
for(int i = 0; i < = 0; i++) send_signal(&res,i);
}
]]>
    </b>
    <c/>
    <d>Text</d>
    <d>Text</d>
    <e>
        <f><g>Text</g></f>
        <f><h>Text</h></f>
    </e>
    
</arrel>
