=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio7/ejercicio7.3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT alumnes (alumne, alumne)>
<!ELEMENT alumne (nom, cognoms, Edat, ciutat, adreca+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognoms (cognom, cognom)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT Edat (#PCDATA)>
<!ELEMENT ciutat (#PCDATA)>
<!ELEMENT adreca (carrer, numero, pis, porta, cp)>
<!ELEMENT carrer (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT pis (#PCDATA)>
<!ELEMENT porta (#PCDATA)>
<!ELEMENT cp (#PCDATA)>

=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio7/ejercicio7.3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnes SYSTEM "ejercicio7.3.dtd">
<alumnes>
    <alumne>
        <nom>Juan Diego</nom>
        <cognoms>
            <cognom>PÃ©rez</cognom>
            <cognom>Mohedano</cognom>
        </cognoms>
        <Edat>27</Edat>
        <ciutat>Viladecans</ciutat>
        <adreca>
            <carrer>Pstg. Dos de Mayo</carrer>
            <numero>2</numero>
            <pis>4</pis>
            <porta>1</porta>
            <cp>08440</cp>
        </adreca>
    </alumne>
    <alumne>
        <nom>Sergi</nom>
        <cognoms>
            <cognom>Tur</cognom>
            <cognom>Badenas</cognom>
        </cognoms>
        <Edat>27</Edat>
        <ciutat>Barcelona</ciutat>
        <adreca>
            <carrer>Rue del Percebe</carrer>
            <numero>13</numero>
            <pis>1</pis>
            <porta>1</porta>
            <cp>08000</cp>
        </adreca>
        <adreca>
            <carrer>Rue del Pi</carrer>
            <numero>13</numero>
            <pis>1</pis>
            <porta>1</porta>
            <cp>08020</cp>
        </adreca>
        
    </alumne>
</alumnes>
