=== alexcatmu/CFGS_DAM/PRIMERO/XML/EXAMEN/examen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT base (aa | (be, be) | c)+ >
<!ELEMENT aa ((dd, dd) | (pe)) >
<!ELEMENT dd (#PCDATA) >
<!ELEMENT pe (#PCDATA | i)* >
<!ELEMENT i (#PCDATA) >
<!ELEMENT be (ka, ele, ele, m?, ((n, o) | (o, n))) >
<!ELEMENT ka (#PCDATA) >
<!ELEMENT ele EMPTY >
<!ELEMENT m (#PCDATA) >
<!ELEMENT n (#PCDATA) >
<!ELEMENT o (#PCDATA) >
<!ELEMENT c ((z, z, z+) | (y*)) >
<!ELEMENT z (#PCDATA) >
<!ELEMENT y (#PCDATA) >
<!ATTLIST be 
                atri1 ID #REQUIRED>
<!ATTLIST ka
                atri2 (r1 | r2 | r3) #IMPLIED>
<!ATTLIST ele
                atri3 (Ge | He) "Ge">

=== alexcatmu/CFGS_DAM/PRIMERO/XML/EXAMEN/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE base SYSTEM "examen.dtd">
<base>  <!--  Com a poc té un fill. Els seus fills poden aparèixer en qualsevol ordre.-->
    <aa> <!-- Si n'apareixen. Primer model per a fills d'aa-->
        <dd> Text </dd>
        <dd> Text </dd>
    </aa>
    <aa> <!-- segon model per a fills d'aa-->
        <pe> 
            <i/>
            <![CDATA[ Zona CDATA ]]>
            <i/>
        </pe>
    </aa>
    <be atri1="Sa1"> <!-- Sempre, si apareixen, n'apareixen múltiples de dos. Primer model per a b -->
        <ka atri2="r2"></ka>
        <ele atri3="Ge"></ele> <!-- Element sense contingut -->
        <ele atri3="He"></ele>
        <n> Text </n>
        <o></o>
    </be>  
    <be atri1="Sa2"> <!-- Segon model per a b -->
        <ka></ka>
        <ele atri3="He"></ele>
        <ele atri3="He"></ele>
        <m></m>
        <o> Text </o>
        <n></n>
    </be>
    <c> <!-- 3 o més z o 0 o més y. z i y contindran texte -->
    </c>
    <be atri1="Sa3"> <!-- Primer model per a b -->
        <ka atri2="r2"></ka>
        <ele atri3="Ge"></ele> <!-- Element sense contingut -->
        <ele atri3="He"></ele>
        <m></m>
        <n></n>
        <o></o>
    </be>  
    <be atri1="Sa4"> <!-- Segon model per a b -->
        <ka></ka>
        <ele atri3="He"></ele>
        <ele atri3="He"></ele>
        <o></o>
        <n></n>
    </be>
</base>
