=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio 10/ejercicio10.2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT stock (productes+) >
<!ELEMENT productes (producte+) >
<!ELEMENT producte (nom, ((marca, preu) | (preu, marca)), (quantitat_disponible | fer_comanda), distribuidors)>
<!ELEMENT nom (#PCDATA) >
<!ELEMENT marca (#PCDATA) >
<!ELEMENT preu (#PCDATA) >
<!ELEMENT quantitat_disponible (#PCDATA) >
<!ELEMENT fer_comanda (#PCDATA) >
<!ELEMENT distribuidors (distribuidor | fabrica)+ >
<!ELEMENT distribuidor (#PCDATA) >
<!ELEMENT fabrica (nom, adreca, tlf) >
<!ELEMENT adreca (#PCDATA) >
<!ELEMENT tlf (#PCDATA) >

=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio 10/ejercicio10.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stock SYSTEM "ejercicio10.2.dtd">
<stock>
    
    <!--De moment l’stock només contindrà els productes. En el futur potser també altres com matèries primeres...
    -->
    
    <productes>
        <producte>
            <nom>XA Pro II </nom>
            <marca> Salomon </marca>
            <preu> 92 euros </preu>
            
            <!-- Comentaris sobre els següent tag:
                - En cas que hi hagi quantitat disponible s'en mostra la quantitat a través del tag quantitat_disponible 
                - En cas que no hi hagi quantitat disponible es mostra el tag fer_comanda, que en cas que es vulgui fer una comanda tindrà el valor Si, i No altrament.	
            -->
            <quantitat_disponible>120</quantitat_disponible>
            <distribuidors>
                <!--Màxima llibertat als fills tenint en comte que almenys n’aparegui 1
                -->
                <distribuidor>Aresta</distribuidor>
                <distribuidor>Intemperie</distribuidor>
            </distribuidors>
        </producte>
        
        <producte>
            <nom>EL CAP SS SHIRT </nom>
            <marca> Nord Face</marca>
            <preu> 42,67 euros </preu>
            <fer_comanda>no</fer_comanda>
            <distribuidors>
                <distribuidor>Aresta</distribuidor>
                <fabrica>
                    <nom>Algo</nom>
                    <adreca>Polígon industrial 2, Santa Perpètua de Moguda</adreca>
                    <tlf>902 234 123 </tlf>
                </fabrica>
            </distribuidors>
            
        </producte>
        <producte>
            <nom>EL CAP SS SHIRT </nom>
            <!-- En alguns casos el tag preu surt abans que el tag marca , i en altres a l'inrevés, per tant cal tenir en compte que l'ordre pot variar.
                L'ordre de la resta de tags és el que es veu reflexat en aquest document, el seu ordre no varia.
            -->
            <preu> 42,67 euro </preu>
            <marca> Nord Face</marca>
            
            <fer_comanda>Si</fer_comanda>
            <distribuidors>
                <distribuidor>Aresta</distribuidor>
            </distribuidors>
        </producte>
    </productes>
</stock>
