=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio8/ejercicio8.2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT movies (movie | documental)*>
<!ELEMENT movie (title, writer+, producer+, director+, actor*, comments?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT comments (#PCDATA)>
<!ELEMENT documental (titleDoc, writerDoc+, producerDoc+, directorDoc+, commentsDoc?, creditsDoc, creditsDoc+)>
<!ELEMENT titleDoc (#PCDATA)>
<!ELEMENT writerDoc (#PCDATA)>
<!ELEMENT producerDoc (#PCDATA)>
<!ELEMENT directorDoc (#PCDATA)>
<!ELEMENT commentsDoc (#PCDATA)>
<!ELEMENT creditsDoc (#PCDATA)>

=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio8/ejercicio8.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "ejercicio8.2.dtd">
<movies>
    <movie>
        <title>pere</title>
        <writer>referencia</writer>
        <writer>referencia2</writer>
        <producer>productor</producer>
        <director>director</director>
        <director>director2</director>
        <comments>comentari</comments>
    </movie>
    <documental>
        <titleDoc>pere</titleDoc>
        <writerDoc>referencia</writerDoc>
        <producerDoc>productor</producerDoc>
        <directorDoc>director</directorDoc>
        <creditsDoc>els credits</creditsDoc>
        <creditsDoc>els credits2</creditsDoc>
    </documental>	
    <documental>
        <titleDoc>pere</titleDoc>
        <writerDoc>referencia</writerDoc>
        <producerDoc>productor</producerDoc>
        <directorDoc>director</directorDoc>
        <creditsDoc>els credits</creditsDoc>
        <creditsDoc>els credits2</creditsDoc>
        <creditsDoc>els credits</creditsDoc>
        <creditsDoc>els credits2</creditsDoc>
    </documental>	
    <movie>
        <title>pere</title>
        <writer>referencia</writer>
        <writer>referencia2</writer>
        <producer>productor</producer>
        <director>director</director>
        <director>director2</director>
        <comments>comentari</comments>
    </movie>
</movies>
