=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio11/ejercicio11.2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT arrel (aa*) >
<!ELEMENT aa (a, b, d, e, f+) >
<!ELEMENT a (#PCDATA) >
<!ELEMENT b ((c, c, c) | z) >
<!ELEMENT d (#PCDATA) >
<!ELEMENT e (y+ | x*) >
<!ELEMENT f (#PCDATA | g | h | i)* >
<!ELEMENT c (#PCDATA) >
<!ELEMENT y (#PCDATA) >
<!ELEMENT g (#PCDATA) >
<!ELEMENT h (#PCDATA) >
<!ELEMENT z (#PCDATA) >
<!ELEMENT x EMPTY >
<!ELEMENT i (#PCDATA) >

=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio11/ejercicio11.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arrel SYSTEM "ejercicio11.2.dtd">
<arrel>  <!-- 0 o més fills -->
    <!-- els elements sense contingut són buits-->
    <aa>
        <a>TEXT</a>
        <b>
            <c> TEXT </c> <!-- Si surten c's són el exactament 3 -->
            <c> TEXT </c>
            <c> TEXT </c>
        </b>
        <d> TEXT </d>
        <e>
            <y>text</y> <!-- un o més -->
            <y>text</y>
        </e>
        <f> <!-- un o més -->
            <g> TEXT </g>
            <h> TEXT </h>
        </f>
    </aa>
    <aa>
        <a> TEXT </a>
        <b>
            <z> TEXT </z> <!-- Una -->
        </b>
        <d> TEXT </d>
        <e>
            <!-- 0 o més elements x -->
        </e>
        <f>
            <g> TEXT </g>
        </f>
        <f>
            <g> TEXT </g>
            TEXT
            <h> TEXT </h>
            <i></i> <!-- PODRÀ CONTENIR QUALSEVOL TIPUS DE CONTINGUT I ESTRUCTURA -->
        </f>
        
    </aa>
    
</arrel>
