=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio11/ejercicio11.1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT arrel (aa+) >
<!ELEMENT aa (a, b, d, e, f+) >
<!ELEMENT a (#PCDATA) >
<!ELEMENT b (c, c, c) >
<!ELEMENT d (#PCDATA) >
<!ELEMENT e EMPTY >
<!ELEMENT f (g, h, i?) >
<!ELEMENT c (#PCDATA) >
<!ELEMENT g (#PCDATA) >
<!ELEMENT h (#PCDATA) >
<!ELEMENT i EMPTY >

=== alexcatmu/CFGS_DAM/PRIMERO/XML/ejercicio11/ejercicio11.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arrel SYSTEM "ejercicio11.1.dtd">
<arrel>  <!-- 1 o més fills -->
    <!-- els elements sense contingut són buits-->
    <aa>
        <a>TEXT</a>
        <b>
            <c> TEXT </c> <!-- exactament 3 -->
            <c> TEXT </c>
            <c> TEXT </c>
        </b>
        <d> TEXT </d>
        <e/>
        <f> <!-- un o més -->
            <g> TEXT </g>
            <h> TEXT </h>
        </f>
    </aa>
    <aa>
        <a> TEXT </a>
        <b>
            <c> TEXT </c>
            <c> TEXT </c>
            <c> TEXT </c>
            
        </b>
        <d> TEXT </d>
        <e/>
        <f>
            <g> TEXT </g>
            <h> TEXT </h>
        </f>
        <f>
            <g> TEXT </g>
            <h> TEXT </h>
            <i/>
        </f>
        
    </aa>
</arrel>
